equipos/config/routes.rb
Rails.application.routes.draw do

  resources :vencimientos
  resources :equipos
  resources :rol_opcion_operaciones
  resources :opciones
  resources :valor_parametros
  resources :usuarios
  root 'seguridad#login'
  resources :parametros
  post '/auth', to:'seguridad#autenticar'
  get '/inicio', to:'inicio#casa'
  get '/logout', to:'seguridad#logout'
  get '/valp/:id', to: "valor_parametros#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

equipos/app/models/vencimiento.rb
# == Schema Information
#
# Table name: vencimientos
#
#  id                  :integer          not null, primary key
#  Equipo_id           :integer
#  FechaInicion        :date
#  FechaFinal          :date
#  Comentario          :string
#  IdTipoVencimiento   :string
#  IdEstadoVencimiento :string
#  Referencia          :string
#  eliminado           :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Vencimiento < ApplicationRecord
  belongs_to :Equipo
end

equipos/app/controllers/vencimientos_controller.rb
class VencimientosController < BaseController
  before_action :set_vencimiento, only: [:show, :edit, :update, :destroy]

  # GET /vencimientos
  # GET /vencimientos.json
  def index
    @vencimientos = Vencimiento.all
  end

  # GET /vencimientos/1
  # GET /vencimientos/1.json
  def show
  end

  # GET /vencimientos/new
  def new
    @vencimiento = Vencimiento.new
  end

  # GET /vencimientos/1/edit
  def edit
  end

  # POST /vencimientos
  # POST /vencimientos.json
  def create
    @vencimiento = Vencimiento.new(vencimiento_params)

    respond_to do |format|
      if @vencimiento.save
        format.html { redirect_to @vencimiento, notice: 'Vencimiento was successfully created.' }
        format.json { render :show, status: :created, location: @vencimiento }
      else
        format.html { render :new }
        format.json { render json: @vencimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vencimientos/1
  # PATCH/PUT /vencimientos/1.json
  def update
    respond_to do |format|
      if @vencimiento.update(vencimiento_params)
        format.html { redirect_to @vencimiento, notice: 'Vencimiento was successfully updated.' }
        format.json { render :show, status: :ok, location: @vencimiento }
      else
        format.html { render :edit }
        format.json { render json: @vencimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vencimientos/1
  # DELETE /vencimientos/1.json
  def destroy
    @vencimiento.destroy
    respond_to do |format|
      format.html { redirect_to vencimientos_url, notice: 'Vencimiento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vencimiento
      @vencimiento = Vencimiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vencimiento_params
      params.require(:vencimiento).permit(:Equipo_id, :FechaInicion, :FechaFinal, :Comentario, :IdTipoVencimiento, :IdEstadoVencimiento, :Referencia, :eliminado)
    end
end

equipos/app/helpers/vencimientos_helper.rb
module VencimientosHelper
end

equipos/app/views/vencimientos/_form.html.erb
 <%= form_with(model: vencimiento, local: true) do |form| %>
  <% if vencimiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vencimiento.errors.count, "error") %> prohibited this vencimiento from being saved:</h2>

      <ul>
      <% vencimiento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-sm-2">
    <%= form.label :Equipo_id %>
    <%= form.text_field :Equipo_id, id: :vencimiento_Equipo_id %>
  </div>

  <div class="form-group col-sm-6">
    <%= form.label :FechaInicion %>
    <%= form.date_select :FechaInicion, id: :vencimiento_FechaInicion %>
  </div>

  <div class="form-group col-sm-6">
    <%= form.label :FechaFinal %>
    <%= form.date_select :FechaFinal, id: :vencimiento_FechaFinal %>
  </div>

  <div class="form-group col-sm-2">
    <%= form.label :Comentario %>
    <%= form.text_field :Comentario, id: :vencimiento_Comentario %>
  </div>

  <div class="form-group col-sm-2">
    <%= form.label :IdTipoVencimiento %>
    <%= form.text_field :IdTipoVencimiento, id: :vencimiento_IdTipoVencimiento %>
  </div>

  <div class="form-group col-sm-2">
    <%= form.label :IdEstadoVencimiento %>
    <%= form.text_field :IdEstadoVencimiento, id: :vencimiento_IdEstadoVencimiento %>
  </div>

  <div class="form-group col-sm-2">
    <%= form.label :Referencia %>
    <%= form.text_field :Referencia, id: :vencimiento_Referencia %>
  </div>

  <div class="form-group col-sm-2">
    <%= form.label :eliminado %>
    <%= form.text_field :eliminado, id: :vencimiento_eliminado %>
  </div>

    <div class="actions">
    <%= form.submit "Guardar", :class=>"btn btn-secondary" %>
  </div>
<% end %>

equipos/app/views/vencimientos/edit.html.erb
  <h4>Modificar Vencimiento</h4>
<%= link_to 'Mostrar', @vencimiento,class:"btn btn-warning" %> <%= link_to 'Regresar', vencimientos_path,class:"btn btn-info" %>
<hr class="division">
<%= render 'form', vencimiento: @vencimiento %>

equipos/app/views/vencimientos/index.html.erb
   <div class="container">
 <p id="notice"><%= notice %></p>

<h4>Vencimientos</h4>

<div class="navbar "> 
<%= link_to 'Nuevo', new_vencimiento_path,class:'btn btn-primary btn-sm' %>
</div>
<table class="table table-bordered">
  <thead >
    <tr>
      <th>id</th>
      <th>Fechainicion</th>
      <th>Fechafinal</th>
      <th>Comentario</th>
      <th>Idtipovencimiento</th>
      <th>Idestadovencimiento</th>
      <th>Referencia</th>
      <th>Eliminado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vencimientos.each do |vencimiento| %>
      <tr>
        <td><%= vencimiento.Equipo %></td>
        <td><%= vencimiento.FechaInicion %></td>
        <td><%= vencimiento.FechaFinal %></td>
        <td><%= vencimiento.Comentario %></td>
        <td><%= vencimiento.IdTipoVencimiento %></td>
        <td><%= vencimiento.IdEstadoVencimiento %></td>
        <td><%= vencimiento.Referencia %></td>
        <td><%= vencimiento.eliminado %></td>
        <td><%= link_to 'Show', vencimiento %></td>
        <td><%= link_to 'Edit', edit_vencimiento_path(vencimiento) %></td>
        <td><%= link_to 'Destroy', vencimiento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</table>

<br>

equipos/app/views/vencimientos/new.html.erb
   <h4>New Vencimiento</h4>


<%= link_to 'Regresar', vencimientos_path,class:"btn btn-info" %>

<%= render 'form', vencimiento: @vencimiento %>

equipos/app/views/vencimientos/show.html.erb
      <p id="notice"><%= notice %></p>
 
<p>
  <strong>Equipo:</strong>
   <%= @vencimiento.Equipo %>
</p>

<p>
  <strong>FechaInicion:</strong>
  <%= @vencimiento.FechaInicion %>
</p>

<p>
  <strong>FechaFinal:</strong>
 <%= @vencimiento.FechaFinal %>
</p>

<p>
  <strong>Comentario:</strong>
<%= @vencimiento.Comentario %> 
</p> 


<p>
  <strong>IdEstadoVencimiento:</strong>
<%= @vencimiento.IdEstadoVencimiento %>
</p>

<p>
  <strong>Referencia:</strong>
<%= @vencimiento.Referencia %>
</p>


<%= link_to 'Back', equipos_path,:class=>"btn btn-secondary" %>