equipos/config/routes.rb
Rails.application.routes.draw do

  resources :vencimientos
  resources :equipos
  resources :rol_opcion_operaciones
  resources :opciones
  resources :valor_parametros
  resources :usuarios
  root 'seguridad#login'
  resources :parametros
  post '/auth', to:'seguridad#autenticar'
  get '/inicio', to:'inicio#casa'
  get '/logout', to:'seguridad#logout'
  get '/valp/:id', to: "valor_parametros#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

equipos/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

equipos/app/models/equipo.rb
# == Schema Information
#
# Table name: equipos
#
#  id             :integer          not null, primary key
#  Placa          :string
#  Modelo         :string
#  Serie          :string
#  IdEstadoEquipo :string
#  IdTipoEquipo   :string
#  IdArea         :string
#  eliminado      :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Equipo < ApplicationRecord
	has_many:vencimientos
end

equipos/app/models/opcione.rb
# == Schema Information
#
# Table name: opciones
#
#  id           :integer          not null, primary key
#  idpadre      :integer
#  opcion       :string
#  url          :string
#  estadoopcion :string
#  orden        :string
#  eshoja       :boolean
#  controller   :string
#  eliminado    :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Opcione < ApplicationRecord
	has_many :rol_opcion_operacione
end

equipos/app/models/parametro.rb
# == Schema Information
#
# Table name: parametros
#
#  id              :integer          not null, primary key
#  atributo        :string
#  descripcion     :string
#  estadoParametro :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Parametro < ApplicationRecord
	has_many :valor_parametro
	
end

equipos/app/models/rol_opcion_operacione.rb
# == Schema Information
#
# Table name: rol_opcion_operaciones
#
#  id          :integer          not null, primary key
#  idrol       :integer
#  idoperacion :integer
#  eliminado   :integer          default(0)
#  estadorolop :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  opcione_id  :integer
#  usuario_id  :integer
#

class RolOpcionOperacione < ApplicationRecord
	belongs_to :opcione
	belongs_to :usuario
end

equipos/app/models/usuario.rb
# == Schema Information
#
# Table name: usuarios
#
#  id              :integer          not null, primary key
#  usuario         :string
#  idrol           :integer
#  idestadousuario :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  eliminado       :integer          default(0)
#  password        :string
#

include Servicios
class Usuario < ApplicationRecord  
	 before_save :encriptarPass
	
   has_many :rol_opcion_operacione
      
  validates :usuario, presence: true, length: { minimum: 4 },
    uniqueness: { case_sensitive: false,message: "Usuario existe. Verifique" }
  validates :password, presence: {message: "Debe agregar un password valido." }

  scope :sin_eliminados, -> { where(eliminado: 0)   }

  private 
  def encriptarPass 
    if self.password !=nil           	
    	self.password = Digest::MD5.hexdigest(self.password)
    end    
 end

end

equipos/app/models/valor_parametro.rb
# == Schema Information
#
# Table name: valor_parametros
#
#  id                   :integer          not null, primary key
#  parametroId          :integer
#  valor                :string
#  orden                :string(3)
#  estadoValorParametro :string(1)
#  eliminado            :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  parametro_id         :integer
#

class ValorParametro < ApplicationRecord
	 belongs_to :parametro
end

equipos/app/models/vencimiento.rb
# == Schema Information
#
# Table name: vencimientos
#
#  id                  :integer          not null, primary key
#  Equipo_id           :integer
#  FechaInicion        :date
#  FechaFinal          :date
#  Comentario          :string
#  IdTipoVencimiento   :string
#  IdEstadoVencimiento :string
#  Referencia          :string
#  eliminado           :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Vencimiento < ApplicationRecord
  belongs_to :Equipo
end

equipos/app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :auth!
  require "pp"
  private
    def auth!
     if defined?session[:usuario]
        unless session[:logueado] == true
          redirect_to "/"
        end
      else
        redirect_to "/"
      end
    end

    def validarOpcion(uri)
      @arr = uri.split('/')
      @controlador = @arr[3].split("?").first.to_s
      @excepciones = ['doLogin','doDestroySession','postConsolidarFactura','anexosUpdate','anexosDelete','getValidarEquipoExiste',
      'getValidarPersonaExiste','getValidarProveedorExiste','getIdProveedor','getTraerEquiposActivosDos','getTraerPersonasActivos',
      'getTraerProveedoresActivos','getOpcions','getValorParams','getAnexos','getConsumos','getVencimientos','getTraerEquiposActivos']
      @excepciones.each do |excep|
        if excep == @controlador
          return true
        end
      end
      return false
    end


    def validarUsuarioOpcion(controller,idRol)
      if defined?session[:usuario]
        if session[:logueado] == true
          RolOpcionOperacion.joins("INNER JOIN opciones as op ON rol_opcion_operaciones.opcion_id = op.id and
          rol_opcion_operaciones.idrol = #{idRol} and rol_opcion_operacions.estadorol = 'A' and
          op.estadoopcion = 'A' and op.eshoja = true and op.controller = '#{controller}'").exists?
        end
      end
    end

end

equipos/app/controllers/inicio_controller.rb
class InicioController < ApplicationController
	def casa	
	 render layout: "application"
	 #redirect_to "http://elheraldo.co"	
	 #render html: "<h1>Hola mundo cruel</h1>".html_safe
	 #render file: "public/404.html"
	end
	
end

equipos/app/helpers/application_helper.rb
module ApplicationHelper
end

equipos/app/helpers/equipos_helper.rb
module EquiposHelper
end

equipos/app/helpers/inicio_helper.rb
module InicioHelper
end

equipos/app/helpers/opciones_helper.rb
module OpcionesHelper
end

equipos/app/helpers/parametros_helper.rb
module ParametrosHelper
end

equipos/app/helpers/seguridad_helper.rb
module SeguridadHelper
end

equipos/app/helpers/usuario_helper.rb
module UsuarioHelper
end

equipos/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

equipos/app/helpers/vencimientos_helper.rb
module VencimientosHelper
end

equipos/app/helpers/welcome_helper.rb
module WelcomeHelper
end

equipos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>RubyPlus</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>     
    <div class="container">
       <div class="row">
          <div class="col-lg-2">
             <%= image_tag("Logo.png", :class => "logo") %>
          </div>
          <div class="col-lg-10 d-flex justify-content-end">

              <div class="dropdown">
                     
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">

                        <i class="fa fa-user fa-fw"></i> 
                        <%= session[:usuario] %> 
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                       <li><a href="#"><i class="fa fa-gear fa-fw"></i>Cambiar Pwd</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="/logout"><i class="fa fa-sign-out fa-fw"></i> Salir</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </div>
          </div>
       </div>
       <div class="row">
             <div class="col-lg-2"> <!-- inicio navegador -->           
              <div id="accordion" role="tablist" class="navegador">
                <div class="card mt-5">
                  <div class="card-header" role="tab" id="headingOne">
                    <h5 class="mb-0">
                      <a data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Básicas
                      </a>
                    </h5>
                  </div>

                  <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
                    <div class="card-body">
                       <ul class="nav">
                       <li>
                            <%= link_to 'Equipos',equipos_path  %>             
                        </li>
                        <li class="nav-item">
                             <%= link_to 'Vencimientos',vencimientos_path  %>                         
                        </li>
                        
                      </ul>
                    </div>
                  </div>
                </div>
              <div class="card">
                <div class="card-header" role="tab" id="headingTwo">
                  <h5 class="mb-0">
                    <a class="collapsed" data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      Definir
                    </a>
                  </h5>
                </div>
                <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
                  <div class="card-body">
       
                </div>
              </div>
            </div>
            <div class="card">
              <div class="card-header" role="tab" id="headingThree">
                <h5 class="mb-0">
                  <a class="collapsed" data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Configurar 
                  </a>
                </h5>
              </div>
              <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion">
            <div class="card-body">
              <ul class="nav">
               <li>
                    <%= link_to 'Usuarios',usuarios_path %>             
                </li>
                <li class="nav-item">
                     <%= link_to 'Parametros',parametros_path %>                         
                </li>
                <li class="nav-item">
                     <%= link_to 'Valor Parametros',valor_parametros_path %>                         
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
        </div><!-- fin del navegador -->
        <div class="col-lg-10">
            <%= yield %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
        $(function() {
           $('[data-toggle="tooltip"]').tooltip()
          })
     </script>
  
  </body>
</html>

equipos/app/views/layouts/application1.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Equipos</title>
     <meta charset="utf-8">
    <%= csrf_meta_tags %>
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>