equipos/config/routes.rb
Rails.application.routes.draw do

  resources :vencimientos
  resources :equipos
  resources :rol_opcion_operaciones
  resources :opciones
  resources :valor_parametros
  resources :usuarios
  root 'seguridad#login'
  resources :parametros
  post '/auth', to:'seguridad#autenticar'
  get '/inicio', to:'inicio#casa'
  get '/logout', to:'seguridad#logout'
  get '/valp/:id', to: "valor_parametros#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

equipos/app/models/parametro.rb
# == Schema Information
#
# Table name: parametros
#
#  id              :integer          not null, primary key
#  atributo        :string
#  descripcion     :string
#  estadoParametro :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Parametro < ApplicationRecord
	has_many :valor_parametro
	
end

equipos/app/controllers/parametros_controller.rb
class ParametrosController < BaseController
  before_action :set_parametro, only: [:show, :edit, :update, :destroy]

  # GET /parametros
  # GET /parametros.json
  def index
    @parametros = Parametro.all
  end

  # GET /parametros/1
  # GET /parametros/1.json
  def show
    render "show1"
  end

  # GET /parametros/new
  def new
    @parametro = Parametro.new
  end

  # GET /parametros/1/edit
  def edit
  end

  # POST /parametros
  # POST /parametros.json
  def create
    @parametro = Parametro.new(parametro_params)

    respond_to do |format|
      if @parametro.save
        format.html { redirect_to @parametro, notice: 'Parametro was successfully created.' }
        format.json { render :show, status: :created, location: @parametro }
      else
        format.html { render :new }
        format.json { render json: @parametro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parametros/1
  # PATCH/PUT /parametros/1.json
  def update
    respond_to do |format|
      if @parametro.update(parametro_params)
        format.html { redirect_to @parametro, notice: 'Parametro was successfully updated.' }
        format.json { render :show, status: :ok, location: @parametro }
      else
        format.html { render :edit }
        format.json { render json: @parametro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parametros/1
  # DELETE /parametros/1.json
  def destroy
    @parametro.destroy
    respond_to do |format|
      format.html { redirect_to parametros_url, notice: 'Parametro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parametro
      @parametro = Parametro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parametro_params
      params.require(:parametro).permit(:atributo, :descripcion, :estadoParametro)
    end
end

equipos/app/helpers/parametros_helper.rb
module ParametrosHelper
end

equipos/app/views/parametros/_form.html.erb
<%= form_with(model: parametro, local: true) do |form| %>
  <% if parametro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parametro.errors.count, "error") %> prohibited this parametro from being saved:</h2>

      <ul>
      <% parametro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :atributo %>
    <%= form.text_field :atributo, id: :parametro_atributo %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :parametro_descripcion %>
  </div>

  <div class="field">
    <%= form.label :estadoParametro %>
    <%= form.text_field :estadoParametro, id: :parametro_estadoParametro %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

equipos/app/views/parametros/edit.html.erb
<h1>Editing Parametro</h1>

<%= render 'form', parametro: @parametro %>

<%= link_to 'Show', @parametro %> |
<%= link_to 'Back', parametros_path %>

equipos/app/views/parametros/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Parámetros</h4>
<%= link_to 'Nuevo', new_parametro_path,class:'btn btn-primary btn-sm' %>
<hr>

<table id="parametros_data" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Id</th>
      <th>Atributo</th>
      <th>Descripcion</th>
      <th>Estado</th>     
    </tr>
  </thead>

  <tbody>
    <% @parametros.each do |parametro| %>
      <tr>     
         <td><a class="llaves" href="/parametros/<%= parametro.id %>"><%= parametro.id %></a></td>   
        <td><%= parametro.atributo %></td>
        <td><%= parametro.descripcion %></td>
        <td><%= parametro.estadoParametro %></td>        
      </tr>
    <% end %>
  </tbody>
</table>
 <script>
    jQuery.noConflict();
    jQuery(document).ready(function(){     
      jQuery('#parametros_data').DataTable(); 
    
    });  
</script>

equipos/app/views/parametros/new.html.erb
<h1>New Parametro</h1>

<%= render 'form', parametro: @parametro %>

<%= link_to 'Back', parametros_path %>

equipos/app/views/parametros/show.html.erb
<h4> Información de Parámetro</h4>
<hr>
<div class="container">
 <%= link_to 'Regresar', parametros_path,class:"btn btn-info" %>	
 <p id="notice"><%= notice %></p>

	<form >

	  <div class="form-group col-md-4">
	    <label >Atributo:</label>
	    <input type="text" class="form-control" value="<%= @parametro.atributo %>" readonly>
	  </div>


	  <div class="form-group col-md-4">
	    <label >Descripción:</label>
	    <input type="text" class="form-control" value="<%= @parametro.descripcion %>" readonly>
	  </div>

	  <div class="form-group col-md-4">
	    <label >Estado:</label>
	    <input type="text" class="form-control" value=" <%= @parametro.estadoParametro %>" readonly>
	  </div>
	</form>
	<%= link_to 'Modificar', edit_parametro_path(@parametro),class:"btn btn-success" %> 
</div>

equipos/app/views/parametros/show1.html.erb
<h4> Información de Parámetro</h4>
<hr class="division">
<div class="container" id="contenido">
 <%= link_to 'Regresar', parametros_path,class:"btn btn-info" %>	
 <%= link_to 'Modificar', edit_parametro_path(@parametro),class:"btn btn-success" %> 
 <p id="notice"><%= notice %></p>
 
 <table class="table">
  	<tr>
  		<td>Id</td>
 		<td>Atributo</td>
        <td>Descripción</td>
        <td>Estado</td>
 	</tr>
 	<tr>
 		<td><%= @parametro.id %></td>
 		<td><%= @parametro.atributo %></td>
 		<td><%= @parametro.descripcion %></td>
    <td><%= @parametro.estadoParametro %></td>
 	</tr> 
 </table>
 <hr>
 <iframe id="valp" src="/valp/<%= @parametro.id %>" frameborder="0" style="border:0;width:100%;height:600px;" scrolling="no"></iframe>
	</div>

 